# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            syrianspock.github.io
tagline:          '[syrianspock.github.io]'
description:      'A blog about robotics and embedded systems'
url:              syrianspock.github.io
baseurl:          '/'

author:
  name:           'Salah Missri'
  url:            https://twitter.com/syrianspock

exclude: [README.md, .bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]

gems:
  - jekyll-feed
  - jekyll-sitemap
