# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            syrianspock.github.io
tagline:          '[syrianspock.github.io]'
description:      'A blog about robotics and embedded systems'
url:              syrianspock.github.io
baseurl:          /

author:
  name:           'Salah-Eddine Missri'
  url:            https://twitter.com/syrianspock

paginate:         5

gems: [jekyll-paginate, jekyll-feed]
